version: '3'

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

services:

  mysql:
    # https://hub.docker.com/_/mysql
    image: mysql:${MYSQL_VERSION}
    command: --default-authentication-plugin=mysql_native_password
    command: mysqld --sql_mode=""
    restart: always
    environment:
      - MYSQL_USER=${PMA_USER}
      - MYSQL_PASSWORD=${PMA_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ~/jydock/mysql-data:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    # command: bash -c "sed -i 's,^post_max_size =.*$,post_max_size = 2048M,' php.ini"
    restart: always
    environment:
      # - PMA_ARBITRARY=1
      - PMA_HOST=${PMA_DB_ENGINE}
      - MYSQL_USER=${PMA_USER}
      - MYSQL_PASSWORD=${PMA_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - "./phpmyadmin/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini"
    ports:
      - "${PMA_PORT}:80"
    depends_on:
      - "${PMA_DB_ENGINE}"
    networks:
      - frontend
      - backend

  apache2:
    # https://github.com/romeOz/docker-apache-php
    image: romeoz/docker-apache-php:${APACHE_PHP_VERSION}
    restart: always
    working_dir: /var/www
    volumes:
      - ./apache2/vhost.conf:/etc/apache2/sites-enabled/app.conf
      - ${APP_CODE_PATH_HOST}:/var/www/
      - ${APACHE_SITES_PATH}:/etc/apache2/sites-available
    ports:
      - "80:80"
    depends_on:
      - "phpmyadmin"
    networks:
      - backend
      - frontend

  apache2_8000:
    # https://github.com/romeOz/docker-apache-php
    image: romeoz/docker-apache-php:${PORT_8000_APACHE_PHP_VERSION}
    restart: always
    working_dir: /var/www
    volumes:
      - ./apache2/vhost.conf:/etc/apache2/sites-enabled/app.conf
      - ${PORT_8000_APP_CODE_PATH_HOST}:/var/www/
      - ${PORT_8000_APACHE_SITES_PATH}:/etc/apache2/sites-available
    ports:
      - "8000:80"
    depends_on:
      - "phpmyadmin"
    networks:
      - backend
      - frontend

  homestead:
    image: shincoder/homestead:php${HOMESTEAD_PHP_VERSION}
    restart: always
    working_dir: /var/www
    volumes:
      - "./homestead/alias.sh:/root/.bash_aliases"
      - "../:/codes"
    working_dir: /codes
    links:
      - apache2
      - apache2:localhost.test
      - selenium
    networks:
      - backend
      - frontend
    depends_on:
      - "${PMA_DB_ENGINE}"

  selenium:
    image: selenium/standalone-chrome:3.11.0-antimony
    depends_on:
      - apache2
    links:
      - apache2
      - apache2:localhost.test
    networks:
      - frontend
    ports:
      - 9515:9515
