version: '3'

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

services:

  mysql:
    # https://hub.docker.com/_/mysql
    image: mysql:${MYSQL_VERSION}
    command: --default-authentication-plugin=mysql_native_password
    command: mysqld --sql_mode=""
    restart: "no"
    environment:
      - MYSQL_USER=${PMA_USER}
      - MYSQL_PASSWORD=${PMA_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ~/jydock/mysql-data:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - backend

  mysql2:
    # https://hub.docker.com/_/mysql
    image: mysql:${MYSQL_VERSION}
    command: --default-authentication-plugin=mysql_native_password
    command: mysqld --sql_mode=""
    restart: "no"
    environment:
      - MYSQL_USER=${PMA_USER}
      - MYSQL_PASSWORD=${PMA_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ~/jydock/mysql2-data:/var/lib/mysql
    ports:
      - "1${MYSQL_PORT}:3306"
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    # command: bash -c "sed -i 's,^post_max_size =.*$,post_max_size = 2048M,' php.ini"
    restart: "no"
    environment:
      # - PMA_ARBITRARY=1
      - PMA_HOST=${PMA_DB_ENGINE}
      - MYSQL_USER=${PMA_USER}
      - MYSQL_PASSWORD=${PMA_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - "./phpmyadmin/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini"
    ports:
      - "${PMA_PORT}:80"
    depends_on:
      - "${PMA_DB_ENGINE}"
    networks:
      - frontend
      - backend

  phpmyadmin2:
    image: phpmyadmin/phpmyadmin
    # command: bash -c "sed -i 's,^post_max_size =.*$,post_max_size = 2048M,' php.ini"
    restart: "no"
    environment:
      # - PMA_ARBITRARY=1
      - PMA_HOST=${PMA_DB_ENGINE}2
      - MYSQL_USER=${PMA_USER}
      - MYSQL_PASSWORD=${PMA_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - "./phpmyadmin/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini"
    ports:
      - "1${PMA_PORT}:80"
    depends_on:
      - "${PMA_DB_ENGINE}"
    networks:
      - frontend
      - backend

  web1:
    # https://github.com/romeOz/docker-apache-php
    # image: romeoz/docker-apache-php:${APACHE_PHP_VERSION}
    build: ./php-apache2/php5.4
    restart: "no"
    working_dir: /var/www
    volumes:
      - ${APP_CODE_PATH_HOST}:/var/www
      - ./apache2/vhost.conf:/etc/apache2/sites-enabled/app.conf
      - ${APACHE_SITES_PATH}:/etc/apache2/sites-available
    ports:
      - "80:80"
    depends_on:
      - phpmyadmin
    networks:
      - backend
      - frontend

  web2:
    # https://github.com/romeOz/docker-apache-php
    # image: romeoz/docker-apache-php:${PORT_8000_APACHE_PHP_VERSION}
    build: ./php-apache2/php7.2
    restart: "no"
    working_dir: /var/www
    volumes:
      - ./apache2/vhost.conf:/etc/apache2/sites-enabled/app.conf
      - ${PORT_8000_APP_CODE_PATH_HOST}:/var/www/
      - ${PORT_8000_APACHE_SITES_PATH}:/etc/apache2/sites-available
    ports:
      - "80:80"
    depends_on:
      - phpmyadmin
      - redis
    networks:
      - backend
      - frontend

  web3:
    # https://github.com/romeOz/docker-apache-php
    # image: romeoz/docker-apache-php:${PORT_8001_APACHE_PHP_VERSION}
    build: ./php-apache2/php7.4
    restart: always
    working_dir: /var/www
    volumes:
      - ./apache2/vhost.conf:/etc/apache2/sites-enabled/app.conf
      - ${PORT_8001_APP_CODE_PATH_HOST}:/var/www/
      - ${PORT_8001_APACHE_SITES_PATH}:/etc/apache2/sites-available
    ports:
      - "80:80"
    depends_on:
      - phpmyadmin
      - redis
    networks:
      - backend
      - frontend

  web4:
    # https://github.com/romeOz/docker-apache-php
    # image: romeoz/docker-apache-php:${PORT_8001_APACHE_PHP_VERSION}
    build: ./php-apache2/php8.0
    restart: always
    working_dir: /var/www
    volumes:
      - ./apache2/vhost.conf:/etc/apache2/sites-enabled/app.conf
      - ${PORT_8001_APP_CODE_PATH_HOST}:/var/www/
      - ${PORT_8001_APACHE_SITES_PATH}:/etc/apache2/sites-available
    ports:
      - "80:80"
    depends_on:
      - phpmyadmin
      - redis
    networks:
      - backend
      - frontend
      

  homestead:
    image: shincoder/homestead:php${HOMESTEAD_PHP_VERSION}
    restart: "no"
    working_dir: /var/www
    volumes:
      - "./homestead/alias.sh:/root/.bash_aliases"
      - "./homestead/alias.sh:/home/homestead/.bash_aliases"
      - "../:/codes"
    working_dir: /codes
    ports:
      - "9912:9912"
    links:
      - selenium
    networks:
      - backend
      - frontend
    depends_on:
      - "${PMA_DB_ENGINE}"
      - redis

  selenium:
    image: selenium/standalone-chrome:3.11.0-antimony
    networks:
      - frontend
    ports:
      - "19515:9515"
      
  redis:
    image: 'bitnami/redis:latest'
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - backend
    ports:
      - "16379:6379"
