version: '3'

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

services:

  mysql1:
    # https://hub.docker.com/_/mysql
    image: mysql:${MYSQL_VERSION}
    command: --default-authentication-plugin=mysql_native_password
    command: mysqld --sql_mode=""
    environment:
      - MYSQL_USER=${PMA_USER1}
      - MYSQL_PASSWORD=${PMA_PASSWORD1}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./__volumes/mysql1-data:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - backend

  mysql2:
    # https://hub.docker.com/_/mysql
    image: mysql:${MYSQL_VERSION}
    command: --default-authentication-plugin=mysql_native_password
    command: mysqld --sql_mode=""
    environment:
      - MYSQL_USER=${PMA_USER1}
      - MYSQL_PASSWORD=${PMA_PASSWORD1}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./__volumes/mysql2-data:/var/lib/mysql
    ports:
      - "1${MYSQL_PORT}:3306"
    networks:
      - backend

  phpmyadmin1:
    image: phpmyadmin/phpmyadmin
    # command: bash -c "sed -i 's,^post_max_size =.*$,post_max_size = 2048M,' php.ini"
    environment:
      - PMA_HOST=mysql1
      - MYSQL_USER=${PMA_USER1}
      - MYSQL_PASSWORD=${PMA_PASSWORD1}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - UPLOAD_LIMIT=500M
      - MEMORY_LIMIT=500M
    # volumes:
    #   - "./phpmyadmin/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini"
    ports:
      - "${PMA_PORT1}:80"
    depends_on:
      - mysql1
    networks:
      - frontend
      - backend

  phpmyadmin2:
    image: phpmyadmin/phpmyadmin
    # command: bash -c "sed -i 's,^post_max_size =.*$,post_max_size = 2048M,' php.ini"
    environment:
      - PMA_HOST=mysql2
      - MYSQL_USER=${PMA_USER1}
      - MYSQL_PASSWORD=${PMA_PASSWORD1}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - UPLOAD_LIMIT=500M
      - MEMORY_LIMIT=500M
    # volumes:
    #   - "./phpmyadmin/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini"
    ports:
      - "${PMA_PORT2}:80"
    depends_on:
      - mysql2
    networks:
      - frontend
      - backend

  web1:
    build: ./php-apache2/php5.4
    working_dir: /var/www
    volumes:
      - ./apache2/vhost.conf:/etc/apache2/sites-enabled/app.conf
      - ${WEB1_APP}:/var/www/
      - ${WEB1_APACHE_SITES}:/etc/apache2/sites-available
    ports:
      - "${WEB1_PORT:-80}:80"
    depends_on:
      - phpmyadmin1
    networks:
      - backend
      - frontend

  web2:
    build: ./php-apache2/php7.2
    working_dir: /var/www
    volumes:
      - ./apache2/vhost.conf:/etc/apache2/sites-enabled/app.conf
      - ${WEB2_APP}:/var/www/
      - ${WEB2_APACHE_SITES}:/etc/apache2/sites-available
      - ./php-apache2/php-ini/php.ini:/usr/local/etc/php/conf.d/php.ini
    ports:
      - "${WEB2_PORT:-80}:80"
    depends_on:
      - phpmyadmin1
      - redis
      - artisan
    networks:
      - backend
      - frontend

  web3:
    build: ./php-apache2/php8.0
    working_dir: /var/www
    volumes:
      - ./apache2/vhost.conf:/etc/apache2/sites-enabled/app.conf
      - ${WEB3_APP}:/var/www/
      - ${WEB3_APACHE_SITES}:/etc/apache2/sites-available
      - ./php-apache2/php-ini/php.ini:/usr/local/etc/php/conf.d/php.ini
    ports:
      - "${WEB3_PORT:-80}:80"
    depends_on:
      - phpmyadmin1
      - redis
      - artisan
    networks:
      - backend
      - frontend

  web4:
    build: ./php-apache2/php8.0
    working_dir: /var/www
    volumes:
      - ./apache2/vhost.conf:/etc/apache2/sites-enabled/app.conf
      - ${WEB4_APP}:/var/www/
      - ${WEB4_APACHE_SITES}:/etc/apache2/sites-available
      - ./php-apache2/php-ini/php.ini:/usr/local/etc/php/conf.d/php.ini
    ports:
      - "${WEB4_PORT:-80}:80"
    depends_on:
      - phpmyadmin1
      - redis
      - artisan
    networks:
      - backend
      - frontend

  artisan:
    build: ./php-apache2/php${ARTISAN_VERSION}
    working_dir: /var/www
    volumes:
      - ./apache2/vhost.conf:/etc/apache2/sites-enabled/app.conf
      - ${ARTISAN_APP}:/var/www/
      - ${ARTISAN_APACHE_SITES}:/etc/apache2/sites-available
      - ./php-apache2/php-ini/php.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on:
      - phpmyadmin1
      - redis
      - editor
    networks:
      - backend

  editor:
    build: ./editor
    working_dir: /var/www
    volumes:
      - ./apache2/vhost.conf:/etc/apache2/sites-enabled/app.conf
      - ${EDITOR_APP}:/var/www/
      - ${EDITOR_APACHE_SITES}:/etc/apache2/sites-available
      - ./php-apache2/php-ini/php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - backend

  selenium:
    image: selenium/standalone-chrome:3.11.0-antimony
    networks:
      - frontend
    ports:
      - "19515:9515"
      
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - backend
    ports:
      - "16379:6379"
