version: '3'

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

services:

  mysql:
    image: mysql:${MYSQL_VERSION}
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_USER=${PMA_USER}
      - MYSQL_PASSWORD=${PMA_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      # - PMA_ARBITRARY=1
      - PMA_HOST=${PMA_DB_ENGINE}
      - MYSQL_USER=${PMA_USER}
      - MYSQL_PASSWORD=${PMA_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "${PMA_PORT}:80"
    depends_on:
      - "${PMA_DB_ENGINE}"
    networks:
      - frontend
      - backend

  apache2:
    image: romeoz/docker-apache-php:${APACHE_PHP_VERSION}
    volumes:
      - ${APP_CODE_PATH_HOST}:/var/www/app/
      - ${APACHE_CONF_DIR}:/etc/apache2/sites-enabled/
    ports:
      - "80:80"
    depends_on:
      - "phpmyadmin"
    networks:
      - backend
      - frontend
